base_images:
  base:
    name: "4.12"
    namespace: ocp
    tag: base
  opm-builder:
    name: opm-builder
    namespace: ci
    tag: v1.14.3
binary_build_commands: export GOFLAGS=''
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.18-openshift-4.12
images:
- dockerfile_path: Dockerfile
  from: base
  to: odf-operator
- dockerfile_path: catalog.deps.Dockerfile
  to: odf-operator-catalog-deps
operator:
  bundles:
  - as: odf-operator-bundle
    dockerfile_path: bundle.Dockerfile
    skip_building_index: true
  substitutions:
  - pullspec: quay.io/ocs-dev/odf-operator:latest
    with: pipeline:odf-operator
promotion:
  to:
  - excluded_images:
    - odf-operator-index-gen
    - odf-operator-deps-index
    name: odf-4.12
    namespace: ocp
releases:
  latest:
    integration:
      name: "4.12"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: odf-operator-bundle-e2e-aws
  steps:
    cluster_profile: odf-aws
    env:
      BASE_DOMAIN: makestoragegreatagain.com
    test:
    - as: unit-tests
      commands: |
        GOFLAGS='' make test
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    - as: e2e-tests
      cli: latest
      commands: |
        unset VERSION
        BUNDLE_IMG="$OO_BUNDLE" CATALOG_DEPS_IMG="$OO_CATALOG" make install-odf
        GOFLAGS='' ODF_OPERATOR_INSTALL=false ODF_OPERATOR_UNINSTALL=false make e2e-test
      dependencies:
      - env: OO_BUNDLE
        name: odf-operator-bundle
      - env: OO_CATALOG
        name: pipeline:odf-operator-catalog-deps
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
zz_generated_metadata:
  branch: release-4.12
  org: red-hat-storage
  repo: odf-operator
